### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by tgourley** [hibernating-rhinos/rhino-etl#37]
Found this project while research ETL in .NET Core.  It appears that there has only been one major update in the last 4 years.  Plus there are some pull requests out there (for what appears months) that would make this project .NET Core compatible.

Is this project dead?

Just trying to decide if I want to take the time to either use this project as-is, fork it and maintain my own version, or just move on.  It looks like a good library, so I am trying not to dismiss out-right.

**Comment by ggeurts** [comment]
I am afraid it is not very alive. For the full upgrade to .NET Core some classes are needed that should appear with .NET Core 3. However, if I were to start again I would consider using https://github.com/madhon/ReactiveETL instead.
